### ISSUE TITLE
Question about your anti-piracy script

### ISSUE THREAD

**Issue by farazk86** [nyunesu/web-games#2]
Hi,

Thank you for this excellent write up. I'm sure its helped lots of struggling indie devs :)

My question is about your anti-piracy script. How do I implement it? Do I add it to a gameObject in my opening scene? Or do I have to do something additional?

I know that I'll edit the ``allowedHosts`` for my own case, but just asking how to implement it in my web build? 

Also what is ``file://`` in the allowed hosts? does it not serve the same purpose as ``localhost`` and ``127.0.0.1``

Thanks

**Comment by farazk86** [comment]
RIght, 

So I did just that and added the script to a gameObject in my opening scene. And I dont think its working.

As after the build I uploaded to ``itch.io`` after commenting out the itch.io domains from ``allowedHosts``. But the game still launches and a popup of the rick-roll opens in background. The popup was already blocked by my pop-up blocker.

How is this preventing piracy? Did I not implement this correctly?

Thanks

**Comment by nyunesu** [comment]
Hey, the late answer might not be useful for you anymore but might help others.

Itch.io hosts their game in a different address that itch.io, it's on their documentation. Some other sites do that as well such as Newgrounds or any other website -- it'll work correctly if you use the right address, in your specific case it is `v6p9d9t4.ssl.hwcdn.net `

As for the redundancy with localhosts is because some addons give a different address such as WebServer for Google Chrome.
